name: Check Backend

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - master
  pull_request:
    paths:
      - 'backend/**'
    branches:
      - master
  workflow_dispatch:

jobs:
  check-backend:
    name: Check Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      NODE_ENV: ${{ secrets.NODE_ENV }}
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      DATABASE_TYPE: ${{ secrets.DATABASE_TYPE }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Start dev server (verify backend starts)
        run: |
          timeout 15 pnpm dev | tee server.log &
          sleep 10
          grep -q '\[Main\] server running at' server.log && echo '✅ Backend server running' || (echo '❌ Server failed'; exit 1)
